### Get all presets
GET http://localhost:8080/v1/presets
### Update a preset to stream link
POST http://localhost:8080/v1/preset
### Get all streams
GET http://localhost:8080/v1/streams
### Get a specific stream
GET http://localhost:8080/v1/stream/23
### Create a stream
PUT http://localhost:8080/v1/stream
content-type: application/json

{
    "name":"test",
    "content":"test"
}
### Update a stream
POST http://localhost:8080/v1/stream/2
content-type: application/json

{
    "name":"test",
    "content":"test"
}