### Discover radios
POST http://localhost:8080/v1/radios
### Get radios state
GET http://localhost:8080/v1/radios
### Get radio state
GET http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25
### Websocket, should get bad request
GET http://localhost:8080/v1/radio/ws?uuid=93f9a5e1-814a-400f-9b70-a25210bbcd25
### Renew
POST http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25/renew
### Refresh volume
POST http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25/volume
### Turn off radio
PATCH  http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25
content-type: application/json

{
    "power": false
}

### Turn on radio
PATCH http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25
content-type: application/json

{
    "power": true
}
### Make sure radio is on and play preset
PATCH http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25
content-type: application/json

{
    "preset": 10
}
### Set volume
PATCH http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25
content-type: application/json

{
    "volume": 30
}
### Make sure radio is on, play preset, and set volume
PATCH http://localhost:8080/v1/radio/93f9a5e1-814a-400f-9b70-a25210bbcd25
content-type: application/json

{
    "preset": 1,
    "volume": 3
}
