basePath: /api
definitions:
  http.HTTPError:
    properties:
      message:
        type: string
    type: object
  http.PatchState:
    properties:
      audio_source:
        type: string
      power:
        type: boolean
      preset:
        type: integer
      volume:
        type: integer
    type: object
  model.Build:
    properties:
      built_by:
        type: string
      commit:
        type: string
      date:
        type: string
      release_url:
        type: string
      summary:
        type: string
      version:
        type: string
    type: object
  model.Preset:
    properties:
      title_new:
        description: TitleNew is the overridden title.
        type: string
      url:
        description: URL of the preset.
        type: string
      url_new:
        description: URLNew is the overridden URL.
        type: string
    type: object
  state.Preset:
    properties:
      number:
        description: Number is the preset number.
        type: integer
      title:
        description: Title of the preset.
        type: string
      title_new:
        description: TitleNew is the overridden title.
        type: string
      url:
        description: URL of the preset.
        type: string
      url_new:
        description: URLNew is the overridden URL.
        type: string
    type: object
  state.State:
    properties:
      audio_source:
        description: AudioSource is the audio source.
        type: string
      audio_sources:
        description: AudioSources is the list of available audio sources.
        items:
          type: string
        type: array
      is_muted:
        description: IsMuted represents if the radio is muted.
        type: boolean
      metadata:
        description: Metadata of the current playing stream.
        type: string
      model_name:
        description: ModelName is the model name of the device.
        type: string
      model_number:
        description: ModelNumber is the model number of the device.
        type: string
      name:
        description: Name of the radio.
        type: string
      power:
        description: Power represents if the radio is not in standby.
        type: boolean
      preset_number:
        description: PresetNumber is the current preset that is playing.
        type: integer
      presets:
        description: Presets of the radio.
        items:
          $ref: '#/definitions/state.Preset'
        type: array
      status:
        description: Status is either playing, connecting, or stopped.
        type: string
      title:
        description: Title of the current playing stream.
        type: string
      title_new:
        description: TitleNew is the overridden title.
        type: string
      url:
        description: URL of the stream that is currently selected.
        type: string
      url_new:
        description: URLNew is the overridden URL.
        type: string
      uuid:
        description: UUID of the radio.
        type: string
      volume:
        description: Volume of the radio.
        type: integer
    type: object
info:
  contact: {}
  description: Control your legacy Reciva based internet radios (Crane, Grace Digital,
    Tangent, etc.) via web browser or REST API.
  title: Reciva Web Remote
  version: "1.0"
paths:
  /build:
    get:
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Build'
      summary: Get build
      tags:
      - build
  /presets:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Preset'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: List presets
      tags:
      - presets
    post:
      parameters:
      - description: Preset
        in: body
        name: preset
        required: true
        schema:
          $ref: '#/definitions/model.Preset'
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/http.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: Update preset
      tags:
      - presets
  /presets/{url}:
    get:
      parameters:
      - description: Preset URL
        in: path
        name: url
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Preset'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/http.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: Get preset
      tags:
      - presets
  /radios:
    get:
      responses:
        "200":
          description: OK
      summary: List radios
      tags:
      - radios
    post:
      responses:
        "200":
          description: OK
        "409":
          description: Discovery already in progress
          schema:
            $ref: '#/definitions/http.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: Discover radios
      tags:
      - radios
  /radios/{uuid}:
    get:
      parameters:
      - description: Radio UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Get radio
      tags:
      - radios
  /radios/{uuid}/subscription:
    post:
      parameters:
      - description: Radio UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Refresh radio subscription
      tags:
      - radios
  /radios/{uuid}/volume:
    post:
      parameters:
      - description: Radio UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
      summary: Refresh radio volume
      tags:
      - radios
  /states:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/state.State'
            type: array
      summary: List states
      tags:
      - states
  /states/{uuid}:
    get:
      parameters:
      - description: Radio UUID
        in: path
        name: uuid
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/state.State'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: Get state
      tags:
      - states
    patch:
      parameters:
      - description: Radio UUID
        in: path
        name: uuid
        required: true
        type: string
      - description: Patch state
        in: body
        name: state
        schema:
          $ref: '#/definitions/http.PatchState'
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/state.State'
            type: array
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/http.HTTPError'
      summary: Patch state
      tags:
      - states
swagger: "2.0"
